checks:
    javascript: true

build:
    dependencies:
        #before:
            #- npm install istanbul   # or add it as part of your package.json

    tests:
        override:
            -
                #command: 'istanbul cover --report clover test.js'
                command: 'npm run test-scrutinizer'
                coverage:
                    file: 'coverage/clover.xml'
                    format: 'clover'

build:
    nodes:
        analysis:
            tests:
                override:
                    # Add the respective Scrutinizer analysis for your language like
                    - js-scrutinizer-run
                    # ....
